Employee/urls.py
from django.contrib import admin
from django.urls import path,include

import Employee.views as views

urlpatterns = [
    path('index/',views.index,name = 'employee_index'),
    path('edit_children/',views.edit_children,name = 'employee_edit_children'),
    path('update_child/',views.update_child,name = 'employee_update_child'),

    path('edit_my_info/',views.edit_my_info,name='employee_edit_my_info'),
    path('update_my_info/',views.update_my_info,name='employee_update_my_info'),

    path('todo_list/',views.ToDo_List,name='employee_ToDo_List'),
    path('update_todo_list',views.update_todo_list,name='employ_update_todo_list'),
    path('update_todo_list_read',views.todo_list_read,name='employ_update_todo_list_read'),
    path('delete_update_todo_list',views.delete_todo_list,name='employ_delete_todo_list'),
    path('completed_todo_list',views.complete_todo_list,name='employ_complete_todo_list'),

    path('audit/',views.Audit,name='employee_audit'),
    path('alter_audit',views.add_audit,name='employee_edit_audit'),
]

Manager/urls.py
from django.contrib import admin
from django.urls import path,include

import Manager.views as views
urlpatterns = [
    # path('index/',views.index,name = 'employee_index'),
    # path('edit_children/',views.edit_children,name = 'employee_edit_children'),
    # path('update_child/',views.update_child,name = 'employee_update_child'),
    #
    # path('edit_my_info/',views.edit_my_info,name='employee_edit_my_info'),
    # path('update_my_info/',views.update_my_info,name='employee_update_my_info'),
    #
    # path('todo_list/',views.ToDo_List,name='employee_ToDo_List'),
    # path('update_todo_list',views.update_todo_list,name='employ_update_todo_list'),
    # path('update_todo_list_read',views.todo_list_read,name='employ_update_todo_list_read'),
    # path('delete_update_todo_list',views.delete_todo_list,name='employ_delete_todo_list'),
    # path('completed_todo_list',views.complete_todo_list,name='employ_complete_todo_list'),
    #
    # path('audit/',views.Audit,name='employee_audit'),
    # path('alter_audit',views.add_audit,name='employee_edit_audit'),


    path('index/',views.index,name='manager_index'),
    path('edit_all_children',views.edit_children,name='manager_edit_all_children'),
    path('update_child',views.update_child,name='manager_update_child'),

    path('edit_stuff',views.edit_stuff,name='manager_edit_stuff'),
    path('update_stuff',views.update_stuff,name='manager_update_stuff'),

    path('edit_my_info',views.edit_my_info,name='manager_edit_my'),
    path('update_my_info',views.update_my_info,name='manager_update_my'),

    path('todo_list/',views.ToDo_List,name='manager_ToDo_List'),
    path('update_todo_list', views.update_todo_list, name='manager_update_todo_list'),
    # path('update_todo_list_read', views.todo_list_read, name='manager_update_todo_list_read'),
    # path('delete_update_todo_list', views.delete_todo_list, name='manager_delete_todo_list'),
    # path('completed_todo_list', views.complete_todo_list, name='manager_complete_todo_list'),
    path('audit/',views.Audit,name='manager_edit_audit'),
    path('approve/',views.approve,name='manager_approve'),
]

Welfare_home/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path,include
from App import views
import Employee.urls as Employee_urls
import Manager.urls as Manager_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login, name='login'),
    path('register/',views.register,name = 'register'),
    path('CheckID/',views.CheckID,name = 'CheckID'),
    path('logout/',views.logout,name='logout'),

    path('employee/',include((Employee_urls,'Employee'),namespace='Employee')),
    path('manager/',include((Manager_urls,'Manager'),namespace='Manager')),
]

Employee/views.py
from django.shortcuts import render,HttpResponseRedirect,reverse,HttpResponse

from django.views.generic import View,ListView
# Create your views here.
from django.contrib.auth.hashers import make_password #在注册时，将密码加密后存入
import App.models as models
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator,InvalidPage,EmptyPage,PageNotAnInteger
import json
import  math


def index(request):
    kids = models.Child.objects.filter(employee__num=request.user.username)
    name = models.Employee.objects.get(num=request.user.username).name
    position = models.Employee.objects.get(num=request.user.username).position
    res = []
    for kid in kids:
        res.append(kid)

    user = request.user.username
    todo_list = models.To_doList.objects.filter(employee__num=user,Is_read=False)
    ToDoList_new = models.To_doList.objects.filter(employee__num=user,Is_read=False).count()
    Audit_new = models.Step_parent.objects.filter(sender__num=user,is_send=False).count()
    Audit = models.Step_parent.objects.filter(sender__num=user,is_send=False)
    context = {
        'res': res,
        'ToDoList_new': ToDoList_new,
        'name': name,
        'position': position,
        'Index': 'active',
        'ToDoList':todo_list,
        'Audit_new':Audit_new,
        'Audit':Audit
    }
    return render(request, 'Employee/employee_index.html', context)
def edit_children(request):

    if request.method =='GET':
        kids = models.Child.objects.filter(employee__num=request.user.username)
        name = models.Employee.objects.get(num=request.user.username).name
        position = models.Employee.objects.get(num=request.user.username).position
        res = []
        pn = request.GET.get("pn", 1)
        pn = int(pn)
        for kid in kids:
            res.append(kid)


        # 分页功能
        per_page = 4
        paginator = Paginator(res, per_page)  # 1、查询结果集  2、每一页显示的记录数
        try:
            res = paginator.page(pn)  # 获取某一页记录
        except (EmptyPage, InvalidPage, PageNotAnInteger):
            res = paginator.page(1)
        # 获取总页数
        num_pages = res.paginator.num_pages

        if num_pages >= 5:  # 总页数大于想显示的分页数字
            if pn <= 2:
                start = 1
                end = 6
            elif pn > num_pages - 2:
                start = num_pages - 4
                end = num_pages + 1
            else:
                start = pn - 2
                end = pn + 3
        else:
            start = 1
            end = num_pages + 1

        numbers = range(start, end)

        ToDoList_new = models.To_doList.objects.filter(employee__num=request.user.username,Is_read=False).count()
        Audit_new = models.Step_parent.objects.filter(sender__num=request.user.username, is_send=False).count()
        context = {
            'res': res,
            'ToDoList_new': ToDoList_new,
            'Audit_new':Audit_new,
            'name': name,
            'position': position,
            'Edit':'active',
            'num_pages': num_pages,
            'numbers': numbers,
            'pn': pn,
            'edit_children':'active',
        }

        return render(request, 'Employee/edit_children.html', context)

def update_child(request):

    height = request.GET.get("height",None)
    weight = request.GET.get("weight",None)
    right_sight = request.GET.get("right_sight",None)
    left_sight = request.GET.get("left_sight",None)
    temperature = request.GET.get("temperature",None)
    num = request.GET.get('num',None)
    print(height, weight, right_sight, left_sight, temperature)
    res = {}
    if height is None or weight is None or right_sight is None or left_sight is None or temperature is None:
        res['result'] = 'error'
    elif height is "" or weight is "" or right_sight is "" or left_sight is "" or temperature is "":
        res['result'] = 'error'
    else:
        ress =models.Child.objects.filter(num=num).update(height=height,weight=weight,right_sight=right_sight,left_sight=left_sight,temperature=temperature)
        res['result'] = 'ok'
    return HttpResponse(res['result'])

def edit_my_info(request):

    if request.method == 'GET':
        print(request.user.username)
        name = models.Employee.objects.get(num=request.user.username).name
        position = models.Employee.objects.get(num=request.user.username).position
        user = models.Employee.objects.get(num=request.user.username)

        ToDoList_new = models.To_doList.objects.filter(employee__num=request.user.username,Is_read=False).count()
        Audit_new = models.Step_parent.objects.filter(sender__num=user, is_send=False).count()
        context = {
            'name':name,
            'position':position,
            'ToDoList_new': ToDoList_new,
            'Audit_new':Audit_new,
            'user':user,
            'Edit': 'active',
            'edit_my':'active',
        }
        return render(request,'Employee/edit_my_info.html',context)

def update_my_info(request):
    str = request.GET.get("str", None)
    num = request.GET.get("num",None)
    name = request.GET.get("name",None)
    ethnic_group = request.GET.get('ethnic_group',None)
    gender = request.GET.get('gender',None)
    password = request.GET.get('password',None)
    confirmed_password = request.GET.get('confirmed_password',None)
    edu = request.GET.get('edu',None)
    age = request.GET.get('age',None)
    position = request.GET.get('position',None)
    tele = request.GET.get('tele',None)
    address = request.GET.get('address',None)
    str_origin = request.GET.get('str_origin',None)

    print(password,confirmed_password,age,tele,address)

    if password == '':
        return HttpResponse('password_error')
    if confirmed_password == '':
        return HttpResponse('confirmed_password_error')
    if age == '':
        return HttpResponse('age_error')
    if tele == '':
        return HttpResponse('tele_error')
    if address == '':
        return HttpResponse('address_error')
    if password != confirmed_password:
        return HttpResponse('password_dont_match')

    if str == '':
        str = '无'
    res = User.objects.filter(username=num).update(password=make_password(password))
    res = models.Employee.objects.filter(num=num).update(password=password,age=age,tele=tele,address=address,brief_introduction=str_origin)

    auth.logout(request)
    return HttpResponse('ok')

def ToDo_List(request):
    name = models.Employee.objects.get(num=request.user.username).name
    position = models.Employee.objects.get(num=request.user.username).position
    num = request.user.username
    ToDoList_new = models.To_doList.objects.filter(employee__num=request.user.username,Is_read=False).count()
    Audit_new = models.Step_parent.objects.filter(sender__num=request.user.username, is_send=False).count()
    todoList = models.To_doList.objects.filter(employee__num=request.user.username)
    for item in todoList:
        print(item)

    ids = []

    length = len(todoList)

    res = []
    count = 0
    temp = {}
    temp_2 = []
    for i in range(len(todoList)):
        if count == 3:
            res.append(temp_2)
            temp_2 = []
            count = 0
        print(todoList[i])
        publisher_name = models.Employee.objects.filter(num=todoList[i].publisher.num).values('name')[0]['name']
        temp.update({'publish_time':todoList[i].Publish_time})
        temp.update({'publisher_name':publisher_name})
        temp.update({'topic':todoList[i].topic})
        temp.update({'content':todoList[i].content})
        temp.update({'read':todoList[i].Is_read})
        temp.update({'id':todoList[i].id})
        temp.update({'is_complete':todoList[i].Is_completed})
        ids.append(id)
        temp_2.append(temp)
        temp = {}
        count += 1
    if len(temp_2) != 0:
        res.append(temp_2)
    context = {
        'ToDo_List':'active',
        'name':name,
        'position':position,
        'ToDoList_new':ToDoList_new,
        'Audit_new':Audit_new,
        'user':num,
        'res':res,
    }
    print(res)
    return render(request,'Employee/ToDo_List.html',context)

def update_todo_list(request):
    employee_id = request.GET.get("employee_id", None)
    publisher_id = request.GET.get("publisher_id", None)
    topic = request.GET.get("topic", None)
    content = request.GET.get('content', None)

    print(employee_id,publisher_id,topic,content)
    try:
        employee = models.Employee.objects.get(num=employee_id)
    except:
        return HttpResponse('employee_id_error')
    if employee_id == '':
        return HttpResponse('employee_id_error')
    elif publisher_id == '':
        return HttpResponse('publisher_id_error')
    elif topic == '':
        return HttpResponse('topic_error')
    elif content == '':
        return HttpResponse('content_error')


    employee = models.Employee.objects.get(num=employee_id)
    publisher = models.Employee.objects.get(num=publisher_id)
    info = {
        'publisher':publisher,
        'employee':employee,
        'content':content,
        'topic':topic,
    }

    s = models.To_doList.objects.create(**info)
    return HttpResponse('ok')

def todo_list_read(request):
    id = request.GET.get('id',None)

    print(id)
    res = models.To_doList.objects.filter(id=id).values('Is_read')[0]['Is_read']

    if res == True:
        res = models.To_doList.objects.filter(id=id).update(Is_read=False)
        return HttpResponse('False')
    else:
        res = models.To_doList.objects.filter(id=id).update(Is_read=True)
        return HttpResponse('True')

def delete_todo_list(request):
    id = request.GET.get('id',None)
    res = models.To_doList.objects.filter(id=id).delete()
    return HttpResponse('ok')

def complete_todo_list(request):
    id = request.GET.get('id',None)
    res = models.To_doList.objects.filter(id=id).values(('Is_completed'))[0]['Is_completed']

templates/Employee/ToDo_List.html
{% extends 'Employee/employee_index_base.html' %}
{% block main %}
    {% load staticfiles %}
    {% load filters %}
    <script src="{% static 'js/jquery.js' %}"></script>
    <div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <a id="startmodal" data-toggle="modal" data-target="#Modal" href="#">
            <button class="btn btn-info " id='startmodal' type="button" style="margin-left: 1200px"><i class="fa fa-paste"></i> Add</button>
        </a>
        <div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h3 class="modal-title" id="exampleModalLabel">新增待办</h3>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                        </div>
                        <div class="modal-body">
                            <div class="row">
                                <div class="col-lg-12 order-md-1 offset-sm-0">
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <label for="lastName">Publisher_number</label>
                                            <input name="add_publisher" disabled="disabled" type="text" class="form-control" id="add_publisher" value="{{ user }}">
                                            <div class="invalid-feedback" id="publisher_num_error">
                                                Publisher_number is required.
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <label for="lastName">Recipient_number</label>
                                            <input name="add_recipient" type="text" class="form-control" id="add_recipient" value="{{ item.name }}" required="">
                                            <div class="invalid-feedback" id="recipient_num_error">
                                                 Recipient_number is required.
                                             </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-11 no-padding" style="margin-top: 20px;margin-left: 20px">
                                            <label for="lastName">Topic</label>
                                            <input name="Topic" type="text" class="form-control" id="Topic" value="{{ item.name }}" required="">
                                            <div class="invalid-feedback" id="topic_error">
                                                 Topic is required.
                                             </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-12 no-padding" style="margin-top: 20px">
                                            <label for="lastName">Content</label>
                                            <textarea class="form-control" name="content" id="content" cols="30" rows="10"></textarea>
                                            <div class="invalid-feedback" id="content_error">
                                                 Content is required.
                                             </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>


                      <div class="modal-footer">
                          <span id="tip"> </span>
                        <button id="close_add" type="button" onclick="close_add('{{ user }}')" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button id="save_add" type="button" onclick="add('{{ user }}')" class="btn btn-primary">Save changes</button>
                      </div>
                    </div>
                </div>
        </div>

    </div>
        {% for row in res %}
            <div class="row">
            {%  for item in row %}
                <div class="col-lg-4">
                <div class="ibox">
                    <div class="ibox-title">
                        <h3 style="font-weight: bold">
                                {{ item|get_item:'topic' }}
                        </h3>
                        <div class="ibox-tools">
                            <a class="close-link" id="close_todo" onclick="close_tod('{{ item|get_item:'id' }}')">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="small m-b-xs">
                             <strong>{{ item|get_item:'publisher_name' }}</strong> <span class="text-muted"><i class="fa fa-clock-o"></i>{{ item|get_item:'publish_time' }}</span>
                        </div>
                        <p>
                            {{ item|get_item:'content' }}
                        </p>
                        <div class="row">
                    <div class="col-md-6">
                            <h5>Tags:</h5>
                            {% if item|get_item:'read' == False %}
                                <button class="btn btn-white btn-xs" onclick="read('{{ item|get_item:'id' }}')" id="is_read is_read_{{ item|get_item:'id' }}" type="button">已阅</button>
                                <button disabled="disabled" class="btn btn-primary btn-xs" onclick="read('{{ item|get_item:'id' }}')" id="is_read not_is_read_{{ item|get_item:'id' }}" type="button">未读</button>
                            {% else %}
                                <button disabled="disabled" class="btn btn-primary btn-xs" onclick="read('{{ item|get_item:'id' }}')" id="is_read is_read_{{ item|get_item:'id' }}" type="button">已阅</button>
                                <button class="btn btn-white btn-xs" onclick="read('{{ item|get_item:'id' }}')" id="is_read not_is_read_{{ item|get_item:'id' }}" type="button">未读</button>
                            {% endif %}

                    </div>
                    <div class="col-md-6">
                        <div class="small text-right">
                            <h5>Stats:</h5>
                            {% if item|get_item:'is_complete' == True %}
                                <button  class="btn btn-primary btn-xs" onclick="completed('{{ item|get_item:'id' }}')" id="complete_{{ item|get_item:'id' }}" style="display: inline-block" type="button">已完成</button>
                                <button class="btn btn-danger btn-xs" onclick="completed('{{ item|get_item:'id' }}')" id="not_complete_{{ item|get_item:'id' }}" style="display: none" type="button">未完成</button>
                            {% else %}
                                <button class="btn btn-primary btn-xs" onclick="completed('{{ item|get_item:'id' }}')" id="complete_{{ item|get_item:'id' }}" style="display: none" type="button">已完成</button>
                                <button class="btn btn-danger btn-xs" onclick="completed('{{ item|get_item:'id' }}')" id="not_complete_{{ item|get_item:'id' }}" style="display: inline-block" type="button">未完成</button>
                            {% endif %}
                        </div>
                    </div>
                </div>
                    </div>
                </div>
            </div>
            {%  endfor %}
        </div>
        {% endfor %}
    </div>

    <script type="text/javascript">


        $(function(){
            $('#Modal').modal("hide");
        });


        $(function () {
            $('#recipient_num_error').focus(function () {
                $('#recipient_num_error').css('display','none')
            })
            $('#publisher_num_error').focus(function () {
                $('#publisher_num_error').css('display','none')
            })
            $('#topic_error').focus(function () {
                $('#topic_error').css('display','none')
            })
            $('#content_error').focus(function () {
                $('#content_error').css('display','none')
            })
        })

        {#$('#save_add').click(function () {#}
        {#        var employee_id = $('#add_recipient').val()#}
        {#        var publisher_id = $('#add_publisher').val()#}
        {#        var topic = $('#Topic').val()#}
        {#        var content = $('#content').val()#}
        {#        $.get('{% url "Employee:employ_update_todo_list" %}',{'employee_id':employee_id,'publisher_id':publisher_id,'topic':topic,#}
        {#            'content':content},function (data) {#}
        {#            if( data == 'employee_id_error')#}
        {#                $('#recipient_num_error').css('display','block');#}
        {#            else if(data == 'publisher_id_error'){#}
        {#                $('#publisher_num_error').css('display','block');#}
        {#            }#}
        {#            else if(data == 'topic_error'){#}
        {#                $('#topic_error').css('display','block');#}
        {#            }#}
        {#            else if(data == 'content_error'){#}
        {#                $('#content_error').css('display','block')#}
        {#            }#}
        {#            else{#}
        {#                $('#tip').html("<span style='color:green'>Success</span>")#}
        {#                $('#add_recipient').val("")#}
        {#                $('#add_publisher').val({{ user }})#}
        {#                $('#Topic').val("");#}
        {#                $('#content').val("");#}
        {#                window.location.reload()#}
        {#            }#}
        {##}
        {#        })#}
        {#})#}
        {#    $('#close_add').click(function () {#}
        {#        $('#add_recipient').val("")#}
        {#        $('#add_publisher').val({{ user }})#}
        {#        $('#Topic').val("");#}
        {#        $('#content').val("");#}
        {#})#}
        function add(id) {
            var employee_id = $('#add_recipient').val()
                var publisher_id = $('#add_publisher').val()
                var topic = $('#Topic').val()
                var content = $('#content').val()
                $.get('{% url "Employee:employ_update_todo_list" %}',{'employee_id':employee_id,'publisher_id':publisher_id,'topic':topic,
                    'content':content},function (data) {
                    if( data == 'employee_id_error')
                        $('#recipient_num_error').css('display','block');
                    else if(data == 'publisher_id_error'){
                        $('#publisher_num_error').css('display','block');
                    }
                    else if(data == 'topic_error'){
                        $('#topic_error').css('display','block');
                    }
                    else if(data == 'content_error'){
                        $('#content_error').css('display','block')
                    }
                    else{
                        $('#tip').html("<span style='color:green'>Success</span>")
                        $('#add_recipient').val("")
                        $('#add_publisher').val(id)
                        $('#Topic').val("");
                        $('#content').val("");
                        window.location.reload()
                    }

                })
        }
        function close_add(id) {
                $('#add_recipient').val("")
                $('#add_publisher').val(id)
                $('#Topic').val("");
                $('#content').val("");
        }
        function read(id) {
            var todo_id = id
            var str1 = '#is_read_'+ id
            var str2 = '#not_is_read_' + id
            $.get('{% url "Employee:employ_update_todo_list_read" %}',{'id':id},function (data) {

                if(data == 'True'){
                    $(str1).attr("class", "btn btn-primary btn-xs");
                    $(str1).attr('disabled','disabled');
                    $(str2).attr("class", "btn btn-white btn-xs");
                    $(str2).removeAttr('disable');
                    console.log(str1);
                }
                else {
                    $(str2).removeClass("btn-white").addClass(("btn-primary"));
                    $(str2).attr('disabled','disabled');
                    $(str1).removeClass("btn-primary").addClass(("btn-white"));
                    $(str1).removeAttr('disable');
                    console.log(str2);
                }
                    window.location.reload()
                })
        }
        function close_tod(id) {
            var num = id;
            $.get('{% url "Employee:employ_delete_todo_list" %}',{"id":id},function (data) {

            })
        }

        function completed(id) {
            var num = id;
            var str1 = "#complete_"+id
            var str2 = "#not_complete_"+id
            $.get('{% url "Employee:employ_complete_todo_list" %}',{"id":id},function (data) {
                if(data=='True'){
                    $(str2).css('display','none')
                    $(str1).css('display','inline-block')
                }
                else{
                    $(str1).css('display','none')
                    $(str2).css('display','inline-block')

                }
            })
        }
    </script>
{% endblock %}